// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwawlyxyvpgdvouesjek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3YXdseXh5dnBnZHZvdWVzamVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDI1OTUsImV4cCI6MjA2MTA3ODU5NX0.STrAK0zYypOthOnSnuF2XUT-1uWRaT5_y-NFuCg69RY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);